version: '3.8'

services:
  redis:
    image: "redis:alpine"

  user:
    build:
      context: ..
      dockerfile: docker/user.Dockerfile
    environment:
      - SQLITE_PATH=../db/database.db

  tweet:
    build:
      context: ..
      dockerfile: docker/tweet.Dockerfile
    environment:
      - SQLITE_PATH=../db/database.db

  follow:
    build:
      context: ..
      dockerfile: docker/follow.Dockerfile
    depends_on:
      - redis
    environment:
      - SQLITE_PATH=../db/database.db

  timeline:
    build:
      context: ..
      dockerfile: docker/timeline.Dockerfile
    environment:
      - SQLITE_PATH=../db/database.db

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/tmp/default.conf
    depends_on:
      - user
      - follow
      - tweet
      - timeline
    ports:
      - "8080:8080"
    environment:
      - NGINX_PORT=8080
    command: /bin/bash -c "envsubst '$$NGINX_PORT' < /tmp/default.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
